### ISSUE TITLE
[Bug] Error on Curseforge, 1.19.2 will install version of 1.18.2

### ISSUE THREAD

**Issue by suerion** [constellation-mc/recipe-book-delight#1]
Hey on Curseforge there is a little Bug of the Versions?

Could you fix this? My Modpack will allways update your Mod.

![Screenshot 2023-05-29 112312](https://github.com/melontini/recipe-book-delight/assets/55131959/86688987-1426-483a-8088-0b88df301792)

**Comment by zenfyrdev** [comment]
Hi, the 1.18.2 version works on all versions between 1.18.2 and 1.19.2. I'll just archive the 1.19.2 only file

**Comment by suerion** [comment]
okey thanks
