### ISSUE TITLE
[Bug] Client throws a netty error if not present on the server

### ISSUE THREAD

**Issue by HaXrDEV** [constellation-mc/recipe-book-delight#3]
**Describe the bug**
If the mod is not present on the server, the client won't be able to join. Just gets a netty error.
(Don't know if this is intended behavior. But though that it should at least be made clear, since i wholeheartedly believed this to be a client-side mod.

**To Reproduce**
1. Have the mod installed on your client but not the server
2. Try to join the server

**Expected behavior**
I should be able to join the server without the mod installed on the server.

**Screenshots**
![image](https://github.com/melontini/recipe-book-delight/assets/20630404/37252ee9-fb3d-4a8f-8e5b-6708e8330e4d)

**Logs**
https://gist.github.com/HaXrBOT/e8f1a525c85ace76a75f5c527dfdfbd4

**Environment:**
 - 1.20.1
 - recipe-book-delight-0.2.0-1.20
 - Fabric

**Comment by zenfyrdev** [comment]
Hi, thanks for the report. I'll see if it's possible to patch out the server requirement.

**Comment by zenfyrdev** [comment]
Unfortunately, this is not possible, since the server refuses to update recipes and fill slots if the recipe type is hidden from RB. I've updated mod's description accordingly.
