### ISSUE TITLE
[Suggestion] Farmer's Delight Refabricated compat for 1.20.1+

### ISSUE THREAD

**Issue by mpustovoi** [constellation-mc/recipe-book-delight#5]
**Is your feature request related to a problem? Please describe.**
A new Farmer's Delight port for Fabric 1.20.1+ has recently appeared

**Describe the solution you'd like**
Switching compatibility to the new Farmer's Delight port for Fabric

**Describe alternatives you've considered**
There are no alternatives, as the old Farmer's Delight port is now marked as Depricated

**Additional context**
https://modrinth.com/mod/farmers-delight-refabricated
> Q. How does this different from the other existing Farmer's Delight Fabric?
> A. This port's main focus has been on simplicity and faithfulness to the original mod. This meant that only minor changes were made to accommodate the loader specific things.
> Package names and all existing behavior has been kept the same. This means that FD addons can now easily be ported from Forge to Fabric with, ideally, no change at all as all the package names are the same.

**Comment by zenfyrdev** [comment]
This port made the add-on obsolete, as it provides the recipe book itself.

**Comment by mpustovoi** [comment]
Thanks for the clarification to me, an amateur
